requires 'FindBin';
requires 'Mojo::IRC';
requires 'Mojolicious';
requires 'Parse::IRC';
requires 'Config::General';
requires 'Net::Twitter::Lite::WithAPIv1_1';
requires 'DateTime';
requires 'DateTime::Format::Duration';
requires 'DateTime::Format::ISO8601';
